apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-deploy
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: web-deploy
  targetCPUUtilizationPercentage: 40
