# Volume Persistence

kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv
 labels:
  type: local
spec:
 storageClassName: mine
 capacity:
   storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume
spec:
  storageClassName: mine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
